version: '3.9'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=super-secret-demo-key
    volumes:
      - ./:/app
    command: bash -lc "python -m app.db.seed && uvicorn app.main:app --host 0.0.0.0 --port 8000"